/**
 * Bulls Traking — Telegram Signal Ingestion Worker (Phase 3 Task 3 Stub)
 * 
 * =========================================================================
 * HOW TO CONNECT A LIVE TELEGRAM CHANNEL VIA @BotFather:
 * =========================================================================
 * 1. Open Telegram and search for @BotFather (verified official bot).
 * 2. Send `/newbot` and follow prompts to choose a name and username (e.g. `BullsTrakingAlertsBot`).
 * 3. Copy the HTTP API token generated by @BotFather.
 * 4. Add the token to your `.env` file:
 *    TELEGRAM_BOT_TOKEN="your_bot_token_here"
 *    TELEGRAM_CHANNEL_ID="@your_channel_or_group_id"
 *    ADMIN_API_KEY="bulls_admin_secret_key"
 * 5. Add your new Bot as an Administrator to your Telegram signals channel with
 *    "Read Messages" permission.
 * 6. Forward a test message or enable webhook/long-polling to this worker.
 * =========================================================================
 */

const { createSignal } = require('../services/signalsService');
const { queryOne } = require('../../database/db');

let isIngestRunning = false;
let pollingInterval = null;

/**
 * Parses raw text from a Telegram post into a structured alpha signal.
 * Supported patterns:
 * - Directives: #BUY, #SELL, #WATCH, LONG, SHORT
 * - Tokens: $SOL, $BTC, $ETH or contract addresses
 * - Content: reasonings, stop loss, targets
 */
function parseTelegramMessage(text) {
  if (!text || typeof text !== 'string') return null;

  const upper = text.toUpperCase();
  let direction = 'watch';

  if (upper.includes('#BUY') || upper.includes('BUY SIGNAL') || upper.includes('LONG') || upper.includes('ENTRY:')) {
    direction = 'buy';
  } else if (upper.includes('#SELL') || upper.includes('SELL SIGNAL') || upper.includes('SHORT') || upper.includes('TAKE PROFIT')) {
    direction = 'sell';
  }

  // Extract potential symbol (e.g., $SOL or #SOL)
  const symbolMatch = text.match(/[\$#]([A-Za-z0-9]{2,10})\b/);
  const symbol = symbolMatch ? symbolMatch[1].toUpperCase() : null;

  let tokenId = null;
  if (symbol) {
    const token = queryOne('SELECT id FROM tokens WHERE UPPER(symbol) = ? LIMIT 1', [symbol]);
    if (token) tokenId = token.id;
  }

  // Generate clean title
  const lines = text.split('\n').map(l => l.trim()).filter(Boolean);
  const title = lines[0] ? lines[0].slice(0, 180) : `Telegram Alpha Signal: ${symbol || direction.toUpperCase()}`;

  return {
    token_id: tokenId,
    title,
    message: text.trim(),
    direction,
    source: 'telegram'
  };
}

/**
 * Ingest a signal payload directly (can be invoked by Webhook or Polling)
 */
function ingestSignal(rawText) {
  const parsed = parseTelegramMessage(rawText);
  if (!parsed) return null;

  try {
    const signal = createSignal(parsed);
    console.log(`[Telegram Ingest] Ingested signal #${signal.id}: "${signal.title}" (${signal.direction})`);
    return signal;
  } catch (err) {
    console.error('[Telegram Ingest Error]', err.message);
    return null;
  }
}

/**
 * Start Telegram ingestion worker.
 * If TELEGRAM_BOT_TOKEN is not configured, logs standby notice.
 */
function startTelegramWorker() {
  const token = process.env.TELEGRAM_BOT_TOKEN;
  const channel = process.env.TELEGRAM_CHANNEL_ID;

  if (!token) {
    console.log('[Telegram Ingest Worker] Standby: TELEGRAM_BOT_TOKEN not set in environment. Ready for webhook/bot config.');
    return;
  }

  console.log(`[Telegram Ingest Worker] Active: listening for signals on channel ${channel || 'All Admin Channels'}...`);
  isIngestRunning = true;

  // Real Telegram getUpdates long-polling loop stub
  // Can be activated with node-telegram-bot-api or standard fetch(https://api.telegram.org/bot<token>/getUpdates)
}

function stopTelegramWorker() {
  if (pollingInterval) clearInterval(pollingInterval);
  isIngestRunning = false;
  console.log('[Telegram Ingest Worker] Stopped.');
}

module.exports = {
  startTelegramWorker,
  stopTelegramWorker,
  parseTelegramMessage,
  ingestSignal
};
